### ISSUE TITLE
Use YAML interface to myApp

### ISSUE THREAD

**Issue by stsievert** [ayonsn017/NEXT#21]
Read the files into memory on the local computer and pass the file contents to NEXT. This will result in

- better documentation of the parameters myApp needs
- no external dependicies, the files. Tests will pass more easily and this is how computer programs should work. What happens when the files are corrupted?

**Comment by stsievert** [comment]
Passing in a file as a string doesn't address my concern. Each file has a specific format: each line has a (string, string, int) or something. We have a system to pass in arguments to the app. Use it.

I don't know if this will effect the speed issues. It will certainly help diminish complication.

**Comment by ayonsn017** [comment]
Different algorithms take as input different types of files. The format within the file are different. Hence I cannot specify it in yaml in a single format.

**Comment by stsievert** [comment]
Looking in `local/data` I see two file types: one JSON object and many different CSVs with (almost) the same header. I'm assuming the CSV files are the different files? This can be worked around.

In the YAML file you can specify a list of dicts. In each dict you can specify the keys. Each key can be optional, which is what I think you're concerned about.

You'd want to pass something like

``` python
[{'mol1': 'HCN', 'rep1': 'SF', 'mol2': 'HCN', 'rep2': 'SF', 'same': True},
 {'mol1': 'H20', 'rep1': 'SF', 'mol2': 'H20', 'rep2': 'SF', 'same': True}
 ...
]
```

where each dictionary could optionally include a probability. This could be done by a YAML snippet like

``` yaml
questions_to_ask:
  type: list
  values:
    type: dict
    values:
      mol1:
        type: str
      rep1:
        type: str
      mol2:
        type: str
      rep2:
        type: str
      same:
        type: bool
      prob:
        type: num
        optional: true  
```

(untested, but it's something like this).
